Task_1_1_3
dariamukomel/OOP pull request #4
Opened 2024-09-26 11:54 UTC by dariamukomel

2024-09-26 15:20 UTC, galinabykova requested changes
мягкий засчитан)

2024-09-26 15:20 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Expression.java
нужно для каждого наследника сделать отдельный файл. И, мне кажется, они должны быть публичными классами

2024-09-26 15:20 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Expression.java
> +    public abstract String print();
лучше переопределить toString, тогда объекты этого класса можно будет удобно выводить, например, в System.out.println
https://www.examclouds.com/ru/java/java-core-russian/method-tostring

2024-09-26 15:20 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/ExpressionParser.java
> +package ru.nsu.lavitskaya;
в след раз называй пакет ru.nsu.lavitskaya.shortLabName, например, ru.nsu.lavitskaya.operations

2024-09-26 15:20 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Expression.java
> +public abstract class Expression {
согласно условию задачи у тебя должен быть eval(String)
![image](https://github.com/user-attachments/assets/a1e4e28a-2579-4862-91b0-afd78bdb6e73)
предлагаю добавить сюда метод
```java
public double eval(String variables) {
    return eval(stringToMap(variables));
}
```
где stringToMap парсит строку и возвращает мапу

2024-09-28 11:19 UTC, galinabykova requested changes
правки reviewdog и документация

2024-09-28 11:19 UTC, galinabykova commented on Task_1_1_3/src/test/java/ru/nsu/lavitskaya/ExpressionTest.java
мне кажется, можно было сделать отдельные тесты на операции, чтобы было проще локализовать ошибку (у тебя проверяются сразу выражения)

2024-09-28 19:00 UTC, galinabykova approved these changes

2024-10-03 17:36 UTC, galinabykova requested changes

2024-10-03 17:36 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Add.java
> +        if (simplifiedLeft.getClass() == Number.class
можно было использовать instanceof
`simplifiedLeft instanceof Number`

2024-10-03 17:36 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Sub.java
> +            String[] terms = simplifiedRight.toString().split("\\+");
вот тут тебе по сути нужны слагаемые, которые ты окольными путями пытаешься получить. В этой ситуации, мне кажется, лучше сделать в Add специальные методы получения поля. Если сделать все поля в выражениях-наследниках final, это будет полностью безопасная операция, так как поля будут неизменяемыми.

Также тут чувствуется, что тебе надо сделать сравнение через equals, очень нужная штука

2024-10-03 17:36 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Sub.java
> +                && simplifiedRight.getClass() == Add.class) {
а simplifiedRight точно должно быть Add? Немного не поняла это упрощение, поясни, пожалуйста

2024-10-03 17:36 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Add.java
> +        if (simplifiedLeft.getClass() == Number.class
они немного отличаются, instanceof вернёт истину, если объект будет либо класса Number, либо его наследника, а == getClass() так не делает. Но здесь это не важно, я написала этот комментарий, просто instanceof чуть-чуть сокращает код. Можешь не менять, просто комментарий, чтобы ты знала, что есть ещё instanceof

2024-10-03 17:36 UTC, galinabykova commented on Task_1_1_3/src/main/java/ru/nsu/lavitskaya/Sub.java
> +            String[] terms = simplifiedRight.toString().split("\\+");
и на всякий случай уточню, что в Java работает приведение типа, можно написать что-то типа (Add)simplifiedRight

2024-10-04 04:36 UTC, dariamukomel commented
Я все таки убрала упрощение с унарным минусом. Там уже в парсере нужно проверять стоит ли после него скобка

2024-10-04 04:39 UTC, dariamukomel commented
Я все таки убрала упрощение с унарным минусом

2024-10-04 05:16 UTC, galinabykova approved these changes

2024-10-13 13:32 UTC, merged