Task_1_2_2
dariamukomel/OOP pull request #6
Opened 2024-10-26 17:52 UTC by dariamukomel

2024-10-27 07:18 UTC, galinabykova requested changes
мягкий засчитан

2024-10-27 07:18 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +public class Node<K, V> {
вообще тут можно было использовать LinkedList, но так тоже можно)

2024-10-27 07:18 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +    final K key;
не уверена, что есть смысл хранить ключ -- он у тебя в в индексе зашит и по идее у всех элементов одного списка одинаков

2024-10-27 07:18 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +        if (!this.key.getClass().equals(otherNode.key.getClass()) ||
мне кажется, это условие можно убрать, потому что equals key и value принимают object. Но, возможно, я  о чём-то не подумала, если это так, поясни

2024-10-27 07:18 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/HashTable.java
> +            modCount++;
у тебя строчки 28-29 и 40-42 одинаковые. Мне кажется, можно избежать дублирования, если аккуратнее реализовать этот метод

2024-11-01 02:40 UTC, dariamukomel commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +    final K key;
индексы это хэшкода ключей, под одним индексом лежит список нодов с одинаковым хэшкодом ключа, а он может быть одинаковым для разных ключей особенно до ресайза

2024-11-01 03:12 UTC, dariamukomel commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +        if (!this.key.getClass().equals(otherNode.key.getClass()) ||
первое условие я оставлю, в контексте сравнения хэш таблиц оно не имеет смысла тк там мы точно знаем что сравниваем классы Node, но для Node как для самостоятельного класса эта проверка нужна. а второе убрала

2024-11-01 03:39 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +    final K key;
а, точно, у меня почему-то перемешались в голове ключи и хэш-коды)

2024-11-01 03:40 UTC, galinabykova commented on Task_1_2_2/src/main/java/ru/nsu/lavitskaya/hashtable/Node.java
> +        if (!this.key.getClass().equals(otherNode.key.getClass()) ||
логично)

2024-11-02 08:49 UTC, galinabykova approved these changes

2024-11-08 06:43 UTC, merged